import {StyleSheet} from 'react-native';

const Typography = StyleSheet.create({
  title1_b_40: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 40,
    lineHeight: 60,
    letterSpacing: 0,
  },
  title2_b_32: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 32,
    lineHeight: 48,
    letterSpacing: 0,
  },
  title3_b_28: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 28,
    lineHeight: 42,
    letterSpacing: 0,
  },
  title4_b_24: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 24,
    lineHeight: 36,
    letterSpacing: 0,
  },
  title5_b_22: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 33,
    letterSpacing: 0,
  },
  subtitle1_b_20: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 30,
    letterSpacing: 0,
  },
  subtitle2_m_20: {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: 20,
    lineHeight: 30,
    letterSpacing: 0,
  },
  subtitle3_b_18: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 27,
    letterSpacing: 0,
  },
  subtitle4_m_18: {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: 18,
    lineHeight: 27,
    letterSpacing: 0,
  },
  subtitle5_b_16: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
  },
  subtitle6_b_14: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0,
  },
  body1_m_16: {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
  },
  body2_m_14: {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0,
  },
  body3_b_12: {
    fontFamily: 'Pretendard',
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0,
  },
  body4_m_12: {
    fontFamily: 'Pretendard',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0,
  },
});

export default Typography;
